services:
  mysql-db:
    container_name: mysql-db
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${SECRET_KEY}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      DB_PORT: 3306
    env_file:
      - .env
    volumes:
      - ./crypto-db.sql:/docker-entrypoint-initdb.d/crypto-db.sql
    networks:
      - web
    restart: always
    

  app:
    container_name: app
    build: ./App
    ports:
      - "3000:3000"
    volumes:
      - ./App:/app
    env_file:
      - .env
    depends_on:
      - mysql-db
    command: "nodejs Backend/index.js"
    networks:
      - web
    restart: on-failure

networks:
  web:
    driver: bridge
